### ISSUE TITLE
Learn registers tests as passing even when they fail

### ISSUE THREAD

**Issue by psan2** [learn-co-curriculum/react-component-updating-lab#3] opened 2019-06-26 14:02 UTC

**Comment by maxwellbenton** [comment] 2019-10-09 20:52
Hi @psan2,

Thank you for spotting this and providing feedback. I was able to replicate the issue you are experiencing, but was unable to identify anything in this lesson's repository that might cause this problem. It seems like this may be something related to Learn itself. I've opened a ticket internally for our engineering team and logged this issue in a separate general issue tracker for React [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3).

As this isn't preventing students from solving the tests and seems to be unrelated to the contents of this repository, I am going to close this issue. We invite you to follow the new issue that is tracking this problem, but either way, we will follow up here when this issue is fully resolved.

**Closed as completed by maxwellbenton** 2019-10-09 20:52 UTC

**Comment by maxwellbenton** [comment] 2019-10-14 17:53
Hi @psan2,

Following up on this issue - Our engineers were able to identify a conflict between the learn gem and some of the dependency versions in this lesson. We've updated the dependencies and confirmed that this lesson will correctly register failed tests for future student forks.

Thank you for bringing this to our attention!
